# Generated by Django 5.1.1 on 2024-09-16 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_curso_remove_professor_area_aluno_delete_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='alunos'),
        ),
    ]
