# Generated by Django 5.1.1 on 2024-09-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0005_alter_aluno_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='imagem',
            field=models.ImageField(null=True, upload_to='alunos'),
        ),
    ]
